### ISSUE TITLE
这个破网站是你搞得吧？这么骗人有意思吗？

### ISSUE THREAD

**Issue by eppeo** [xiaoyanu/Home-page#2]
<img width="881" alt="image" src="https://github.com/xiaoyanu/Home-page/assets/11267559/a243d61e-1354-47d8-b2db-49bb04f7240c">
<img width="939" alt="image" src="https://github.com/xiaoyanu/Home-page/assets/11267559/b768c79a-828b-435d-9049-8133cccabfbe">

**Comment by xiaoyanu** [comment]
你没病吧？自己分不清什么是开源吗？带点脑子来问行吗？怎么你开源的作品还能监管不成？你能监管的到啊？仓库readme你是一点也不看就来发言啊？

**Comment by xiaoyanu** [comment]
你开源了代码，别人拿去干坏事，你来怪罪作者？你脑子有坑是吧？别人拿你开源的代码做坏事，我是不是应该来骂你而不是去骂做坏事的人？带点脑子行么？
